server:
  port: 8080

spring:
  profiles:
    default: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000
        generate_statistics: true
        cache:
          use_second_level_cache: true
          factory_class: org.hibernate.cache.jcache.internal.JCacheRegionFactory
      javax:
        persistence:
          sharedCache:
          mode: ENABLE_SELECTIVE

  cloud:
    aws:
      credentials:
        accessKey: ${S3_ACCESS_KEY}
        secretKey: ${S3_SECRET_KEY}
      s3:
        bucketName: ${S3_BUCKET_NAME}
      region:
        static: ap-northeast-2
      stack:
        auto: false

