server:
  port: 8080

spring:
  profiles:
    default: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pawprint
    username: root
    password: Ksy0780@
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000
        generate_statistics: true
cloud:
  aws:
    s3:
      bucket: pawprint.s3
    credentials:
      accessKey: ${S3_ACCESSKEY}
      secretKey: ${S3_PASSWORD}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false


      #  jwt:
      #    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb